language: go
go:
 - "1.13"
 - "1.14"
 - "1.18"
 - "tip"

addons:
  postgresql: "9.6"

services:
  - postgresql

install:
  - go install
  - npm install less sass -g

before_script:
  - hexya generate -t ./src/tests/testmodule
  - psql -c 'create database hexya_test_models;' -U postgres
  - psql -c 'create database hexya_test_tests;' -U postgres

script:
  - ./run_tests.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)

env:
  - HEXYA_DB_DRIVER=postgres HEXYA_DB_USER=postgres HEXYA_DB_PASSWORD= HEXYA_DB_PREFIX=hexya_test GO111MODULE=on
