package loader

// This file is autogenerated by hexya-generate
// DO NOT MODIFY THIS FILE - ANY CHANGES WILL BE OVERWRITTEN

import (
	"github.com/hexya-erp/hexya/src/models"
)

// ------- MODEL ---------

// ModelMixinModel is a strongly typed model definition that is used
// to extend the ModelMixin model or to get a ModelMixinSet through
// its NewSet() function.
//
// To get the unique instance of this type, call ModelMixin().
type ModelMixinModel struct {
	*models.Model
}

// NewSet returns a new ModelMixinSet instance wrapping the given model in the given Environment
func (md ModelMixinModel) NewSet(env models.Environment, modelName string) models.RecordSet {
	return models.ModelMixinSet{
		RecordCollection: env.Pool(modelName),
	}
}

// NewData returns a pointer to a new empty ModelMixinData instance.
//
// Optional field maps if given will be used to populate the data.
func (md ModelMixinModel) NewData(fm ...models.FieldMap) models.RecordSet {
	return &models.ModelMixinData{
		ModelData: models.NewModelData(ModelMixin(), fm...),
	}
}

// Fields returns the Field Collection of the ModelMixin Model
func (md ModelMixinModel) Fields() models.FieldsCollection {
	return models.FieldsCollection{
		FieldsCollection: md.Model.Fields(),
	}
}

// Methods returns the Method Collection of the ModelMixin Model
func (md ModelMixinModel) Methods() models.MethodsCollection {
	return models.MethodsCollection{
		MethodsCollection: md.Model.Methods(),
	}
}

// Underlying returns the underlying models.Model instance
func (md ModelMixinModel) Underlying() *models.Model {
	return md.Model
}

var _ models.Modeler = ModelMixinModel{}

// Coalesce takes a list of ModelMixinSet and return the first non-empty one
// if every record set is empty, it will return the last given
func (md ModelMixinModel) Coalesce(lst ...m.ModelMixinSet) m.ModelMixinSet {
	var last m.ModelMixinSet
	for _, elem := range lst {
		if elem.Collection().IsNotEmpty() {
			return elem
		}
		last = elem
	}
	return last
}

// ModelMixin returns the unique instance of the ModelMixinModel type
// which is used to extend the ModelMixin model or to get a ModelMixinSet through
// its NewSet() function.
func ModelMixin() ModelMixinModel {
	return ModelMixinModel{
		Model: models.Registry.MustGet("ModelMixin"),
	}
}
